version: '3.3'

networks:
  bigdatanet:
    driver: bridge

services:
  hadoop:
    image: marcelmittelstaedt/spark_base:latest
    container_name: hadoop
    volumes:
      - ./hadoop_vol/startup.sh:/startup.sh
    ports:
      - "8088:8088"
      - "9870:9870"
      - "9864:9864"
      - "10000:10000"
      - "8032:8032"
      - "8030:8030"
      - "8031:8031"
      - "9000:9000"
      - "8888:8888"
    networks:
      - bigdatanet

  airflow:
    image: marcelmittelstaedt/airflow:latest
    container_name: airflow
    volumes:
      - ./airflow_vol/dags:/home/airflow/airflow/dags
      - ./airflow_vol/plugins/:/home/airflow/airflow/plugins
      - ./airflow_vol/spark/:/home/airflow/airflow/spark
    ports:
      - "8080:8080"
    networks:
      - bigdatanet
    depends_on:
      - hadoop
    command: >
      bash -c "airflow db init &&
      airflow webserver &
      airflow scheduler &
      tail -f /dev/null"

